version: 2.1

parameters:
  run-build:
    description: "trigger hello-job"
    type: boolean
    default: false

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello world" # run the `echo` command


workflows:
  my-workflow:
    when: << pipeline.parameters.run-build >>
    jobs:
      - hello-job
    triggers:
      - schedule:
          cron: /5 * * * * # every 5th minute
          filters:
            branches:
              only:
                - master


